### ISSUE TITLE
Ubuntu 25.10 kernel compilation failed

### ISSUE THREAD

**Issue by afajfafaf** [RomikB/amneziawg-install#9]
Ubuntu 25.10 kernel compilation failed

**Comment by afajfafaf** [comment]
debian12.10 and debian13 failed

**Comment by Djoesan** [comment]
Same..

`
...
Настраивается пакет dkms (3.0.11-1ubuntu13) …
Настраивается пакет amneziawg-dkms (1.0.0-0~202510021336+591f50a~ubuntu24.04.1) …
Loading new amneziawg-1.0.0 DKMS files...
Deprecated feature: REMAKE_INITRD (/usr/src/amneziawg-1.0.0/dkms.conf)
Building for 6.8.0-85-generic
Building initial module for 6.8.0-85-generic
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/amneziawg/1.0.0/source/dkms.conf)
Error! Bad return status for module build on kernel: 6.8.0-85-generic (x86_64)
Consult /var/lib/dkms/amneziawg/1.0.0/build/make.log for more information.
dpkg: ошибка при обработке пакета amneziawg-dkms (--configure):
 подпроцесс из пакета amneziawg-dkms установлен сценарий post-installation возвратил код ошибки 10
Настраивается пакет g++-x86-64-linux-gnu (4:13.2.0-7ubuntu1) …
Настраивается пакет g++-13 (13.3.0-6ubuntu2~24.04) …
dpkg: зависимости пакетов не позволяют настроить пакет amneziawg:
 amneziawg зависит от amneziawg-dkms (>= 0.0.20200121-2) | amneziawg-modules (>= 0.0.20191219), однако:
  Пакет amneziawg-dkms пока не настроен.
  Пакет amneziawg-modules не установлен.

dpkg: ошибка при обработке пакета amneziawg (--configure):
 проблемы зависимостей — оставляем не настроенным
Отчёт apport не записан, так как сообщение об ошибке указывает на повторную ошибку от предыдущего отказа.
 Настраивается пакет g++ (4:13.2.0-7ubuntu1) …
update-alternatives: используется /usr/bin/g++ для предоставления /usr/bin/c++ (c++) в автоматическом режиме
Настраивается пакет build-essential (12.10ubuntu1) …
Обрабатываются триггеры для man-db (2.12.0-4build2) …
Обрабатываются триггеры для libc-bin (2.39-0ubuntu8.6) …
При обработке следующих пакетов произошли ошибки:
 amneziawg-dkms
 amneziawg
needrestart is being skipped since dpkg has failed
...`

**Comment by RomikB** [comment]
25.10 was not supported by amneziawg

**Comment by RomikB** [comment]
> `Настраивается пакет dkms (3.0.11-1ubuntu13) … Настраивается пакет amneziawg-dkms (1.0.0-0~202510021336+591f50a~ubuntu24.04.1)

Данная версия пакета проблемная, необходимо дождаться фикса со стороны разработчика amneziawg.
